!classDefinition: #Pepe category: #'Ejercicio 1'!
DenotativeObject subclass: #Pepe
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Pepe class' category: #'Ejercicio 1'!
Pepe class
	instanceVariableNames: ''!

!Pepe class methodsFor: 'as yet unclassified' stamp: 'mf 8/19/2025 21:10:41'!
hola
^'chau'! !
